apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: 837318114635.dkr.ecr.us-east-1.amazonaws.com/recipe-app-api-app-final:new
        ports:
        - containerPort: 9000

        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DJANGO_SECRET_KEY
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASS
        - name: ALLOWED_HOSTS
          value: '*'

        volumeMounts:
        - name: static
          mountPath: /vol/web/static
        - name: media
          mountPath: /vol/web/media

      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: efs-pvc-static

      - name: media
        persistentVolumeClaim:
          claimName: efs-pvc
