apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc   # 🔥 THIS IS REQUIRED
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc   # 🔥 THIS IS REQUIRED
  resources:
    requests:
      storage: 5Gi
