apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: secretkey123
  DB_HOST: mydb3.c4rmigmqaal0.us-east-1.rds.amazonaws.com
  DB_NAME: djangoproject
  DB_USER: djangouser
  DB_PASS: MyStrongPass123
  
