apiVersion: v1
kind: Service

metadata:
  name: django

spec:
  type: {{ .Values.django.service.type }}

  ports:
    - protocol: TCP
      port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.targetPort }}

  selector:
    app: django
