apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.efs.static.claimName }}

spec:
  accessModes:
    - {{ .Values.efs.accessMode }}

  storageClassName: {{ .Values.efs.storageClassName }}

  resources:
    requests:
      storage: {{ .Values.efs.storage }}
