apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.ingress.name }}

  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.healthcheckPath | quote }}

    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.listenPorts | quote }}

    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}

    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}

    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname | quote }}

    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.securityGroupId | quote }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.hostname | quote }}

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: {{ .Values.ingress.backend.serviceName }}
                port:
                  number: {{ .Values.ingress.backend.servicePort }}
