apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-db-secrets
  namespace: default

spec:
  provider: aws

  parameters:
    region: us-east-1
    usePodIdentity: "true"

    objects: |
      - objectName: "django-db-secret"
        objectType: "secretsmanager"

  secretObjects:
    - secretName: app-secret
      type: Opaque

      data:
        - objectName: DJANGO_SECRET_KEY
          key: DJANGO_SECRET_KEY

        - objectName: DB_HOST
          key: DB_HOST

        - objectName: DB_NAME
          key: DB_NAME

        - objectName: DB_USER
          key: DB_USER

        - objectName: DB_PASS
          key: DB_PASS
