app:
  name: django
  replicas: 1
  image:
    repository: 837318114635.dkr.ecr.us-east-1.amazonaws.com/recipe-app-api-app-final
    tag: new
  containerPort: 9000
  allowedHosts: "*"
secrets:
  name: app-secret
persistence:
  staticClaim: efs-pvc-static
  mediaClaim: efs-pvc
services:
  django:
    name: django-service
    type: ClusterIP
    port: 9000
    targetPort: 9000
  nginx:
    name: nginx-service
    type: ClusterIP
    port: 80
    targetPort: 8000
nginx:
  name: nginx
  replicas: 1
  image:
    repository: 837318114635.dkr.ecr.us-east-1.amazonaws.com/recipe-app-api-proxy-final
    tag: new
  containerPort: 8000
  appHost: django-service
  appPort: "9000"
persistence:
  accessMode: ReadWriteMany
  storageClassName: efs-sc
  size: 5Gi
  mediaClaim: efs-pvc
  staticClaim: efs-pvc-static
ingress:
  name: django-ingress
  className: alb
  scheme: internet-facing
  targetType: ip
  listenPorts: '[{"HTTP":80},{"HTTPS":443}]'
  certificateArn: arn:aws:acm:us-east-1:837318114635:certificate/1927b153-b4d3-4384-8edc-8fd202ed0221
  sslRedirect: "443"
  host: app.mahesh1249.store
  serviceName: nginx-service
  servicePort: 80
secrets:
  name: app-secret
  djangoSecretKey: "secretkey123"
  dbHost: "mydb3.c4rmigmqaal0.us-east-1.rds.amazonaws.com"
  dbName: "djangoproject"
  dbUser: "djangouser"
  dbPass: "MyStrongPass123"
storageClass:
  enabled: true
  name: efs-sc
  provisioner: efs.csi.aws.com
  provisioningMode: efs-ap
  fileSystemId: fs-00dece18a220c0d17
  directoryPerms: "755"
  basePath: "/dynamic_provisioning"
deployments:
  app:
    image:
      tag: sha-f825ed3
  proxy:
    image:
      tag: sha-f825ed3
django:
  image:
    tag: ""
proxy:
  image:
    tag: ""
