apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: django
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.containerPort }}

        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DJANGO_SECRET_KEY
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_PASS
        - name: ALLOWED_HOSTS
          value: "{{ .Values.app.allowedHosts }}"

        volumeMounts:
        - name: static
          mountPath: /vol/web/static
        - name: media
          mountPath: /vol/web/media

      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.staticClaim }}

      - name: media
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.mediaClaim }}
