apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.django.name }}
spec:
  type: {{ .Values.services.django.type }}
  ports:
    - port: {{ .Values.services.django.port }}
      targetPort: {{ .Values.services.django.targetPort }}
  selector:
    app: {{ .Values.app.name }}
