apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"

        ports:
        - containerPort: {{ .Values.nginx.containerPort }}

        env:
        - name: APP_HOST
          value: "{{ .Values.nginx.appHost }}"
        - name: APP_PORT
          value: "{{ .Values.nginx.appPort }}"

        volumeMounts:
        - name: static
          mountPath: /vol/static
          readOnly: true
        - name: media
          mountPath: /vol/media
          readOnly: true

      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.staticClaim }}

      - name: media
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.mediaClaim }}
