apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nginx.name }}
spec:
  type: {{ .Values.services.nginx.type }}
  ports:
    - port: {{ .Values.services.nginx.port }}
      targetPort: {{ .Values.services.nginx.targetPort }}
  selector:
    app: {{ .Values.nginx.name }}
