apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey }}
  DB_HOST: {{ .Values.secrets.dbHost }}
  DB_NAME: {{ .Values.secrets.dbName }}
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASS: {{ .Values.secrets.dbPass }}
