name: Build and Push UI Service to ECR

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - "src/ui/src/**"
      #- ".github/workflows/build-push-ui.yaml" # During testing phases only for prod comment this line

permissions:
  id-token: write # Needed for OIDC
  contents: write # Needed to push commits

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_APP: app
  ECR_REPOSITORY_PROXY: proxy

jobs:
  build-and-push-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::837318114635:role/github-actions-oidc-role-ui3
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Define image tags
      #   id: vars

      - name: Define image tags
        id: vars
        run: |
          SHA_TAG=sha-${GITHUB_SHA::7}

          REGISTRY="${{ steps.login-ecr.outputs.registry }}"

          APP_IMAGE_BASE="$REGISTRY/${{ env.ECR_REPOSITORY_APP }}"
          PROXY_IMAGE_BASE="$REGISTRY/${{ env.ECR_REPOSITORY_PROXY }}"

          echo "APP_IMAGE_BASE=$APP_IMAGE_BASE" >> $GITHUB_ENV
          echo "PROXY_IMAGE_BASE=$PROXY_IMAGE_BASE" >> $GITHUB_ENV
          echo "TAGS=lates $SHA_TAG" >> $GITHUB_ENV
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV

          echo "Using tags: lates and $SHA_TAG"
        # run: |
        #   SHA_TAG=sha-${GITHUB_SHA::7}
        #   IMAGE_BASE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}"
        #   echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
        #   echo "TAGS=latest $SHA_TAG" >> $GITHUB_ENV
        #   echo "Using tags: latest and $SHA_TAG"
        #   echo "latest = convenience tag for testing"
        #   echo "$SHA_TAG = immutable tag used in Helm values"
      
      - name: Build and push Docker images
        run: |
          for tag in $TAGS; do

            # APP IMAGE
            APP_IMAGE_URI="$APP_IMAGE_BASE:$tag"
            echo "Building APP image: $APP_IMAGE_URI"
            docker build -t $APP_IMAGE_URI .
            docker push $APP_IMAGE_URI

            # PROXY IMAGE
            PROXY_IMAGE_URI="$PROXY_IMAGE_BASE:$tag"
            echo "Building PROXY image: $PROXY_IMAGE_URI"
            docker build -t $PROXY_IMAGE_URI proxy/
            docker push $PROXY_IMAGE_URI

          done
      # - name: Build and push Docker images
      #   run: |
      #     for tag in $TAGS; do
      
      #       # APP IMAGE
      #       APP_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:$tag"
      #       echo "Building APP image: $APP_IMAGE_URI"
      #       docker build -t $APP_IMAGE_URI src/app
      #       docker push $APP_IMAGE_URI

      #       # PROXY IMAGE
      #       PROXY_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_PROXY }}:$tag"
      #       echo "Building PROXY image: $PROXY_IMAGE_URI"
      #       docker build -t $PROXY_IMAGE_URI src/proxy
      #       docker push $PROXY_IMAGE_URI

      #     done 




      # - name: Build and push Docker images
      #   run: |
      #     for tag in $TAGS; do
      #       IMAGE_URI="$IMAGE_BASE:$tag"
      #       echo "Building and pushing $IMAGE_URI"
      #       docker build -t $IMAGE_URI src/ui
      #       docker push $IMAGE_URI
      #     done

      - name: Setup Git auth using GITHUB_TOKEN
        run: |
          git config --global user.name "ci-bot"
          git config --global user.email "ci-bot@stacksimplify.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Update Helm values file with new image tag
        run: |
          cd django-app/
          pwd
          ls
          # Install yq (YAML-safe processor)
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

          # Git config
          git config user.name "ci-bot"
          git config user.email "ci-bot@stacksimplify.com"

          # Generate new tag
          NEW_TAG="sha-${GITHUB_SHA::7}"
          echo "Updating image tags to: $NEW_TAG"

          # Update APP image tag
          yq -i '.deployments.app.image.tag = "'$NEW_TAG'"' values.yaml

          # Update PROXY image tag
          yq -i '.deployments.proxy.image.tag = "'$NEW_TAG'"' values.yaml

          # Show changes (debug)
          echo "Updated tags:"
          cat values.yaml | grep tag

          # Commit only if changes exist
          git diff --quiet || (
          git add values.yaml
          git commit -m "Update UI image tag to $NEW_TAG"
          git push origin main
          )

      # - name: Update Helm values file with new image tag
      #   run: |
      #     cd src/ui
      #     git config user.name "ci-bot"
      #     git config user.email "ci-bot@stacksimplify.com"
      #     sed -i "/app:/,/tag:/ s|tag: .*|tag: sha-${GITHUB_SHA::7}|" chart/values.yaml
      #     sed -i "/proxy:/,/tag:/ s|tag: .*|tag: sha-${GITHUB_SHA::7}|" chart/values.yaml
      #     git diff --quiet || (
      #       git add chart/values-ui.yaml
      #       git commit -m "Update UI image tag to sha-${GITHUB_SHA::7}"
      #       git push origin main
      #     )

      - name: CI Complete
        run: |
          echo "Image push and Git update done"
          echo "Tags used: $TAGS"
