name: Checks

on:
  # pull_request:
  #   branches:
  #     - main
  # workflow_dispatch:

permissions:
  contents: read

jobs:

  # ============================================================
  # APPLICATION TESTS
  # ============================================================
  test-application:
    name: Test Application
    uses: ./.github/workflows/test-application.yml


  # ============================================================
  # TERRAFORM TESTS
  # ============================================================
  test-terraform:
    name: Test Terraform
    uses: ./.github/workflows/test-terraform.yml
