name: Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - staging
          - prod
env:
  AWS_REGION: us-east-1


jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::837318114635:role/github-actions-oidc-role-ui3
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Destroy
        

        working-directory: infra
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.environment }}

          echo "===== Destroying EKS ====="
          terraform -chdir=deploy/02_EKS_terraform-manifests init
          terraform -chdir=deploy/02_EKS_terraform-manifests workspace show
          terraform -chdir=deploy/02_EKS_terraform-manifests destroy -auto-approve

          
          echo "===== Destroying VPC ====="
          terraform -chdir=deploy/01_VPC_terraform-manifests init
          terraform -chdir=deploy/01_VPC_terraform-manifests destroy -auto-approve
  