name: Deploy

on:
  push:
    branches: [ "main", "prod" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1


jobs:
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    name: Test and Lint
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: [test-lint]
    # strategy:
    #   matrix:
    #     dir:
    #       - deploy/01_VPC_terraform-manifests
    #       - deploy/02_EKS_terraform-manifests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::837318114635:role/github-actions-oidc-role-ui3
          aws-region: ${{ env.AWS_REGION }}
      - name: Set vars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            echo "prod" > .workspace
          else
          echo "staging" > .workspace
          fi
      - name: Debug docker compose
        run: |
          pwd
      - name: Terraform Apply
        working-directory: infra
        run: |  
          workspace=$(cat ../.workspace)
          echo "===== Applying VPC ====="
          docker compose run --rm terraform -chdir=deploy/01_VPC_terraform-manifests init
          docker compose run --rm terraform -chdir=deploy/01_VPC_terraform-manifests workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy/01_VPC_terraform-manifests apply -auto-approve
          docker compose run --rm terraform -chdir=deploy/01_VPC_terraform-manifests output
          echo "===== Applying EKS ====="
          docker compose run --rm terraform -chdir=deploy/02_EKS_terraform-manifests init
          docker compose run --rm terraform -chdir=deploy/02_EKS_terraform-manifests workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy/02_EKS_terraform-manifests apply -auto-approve

